CSW-Teams/MS3

src/main/java/org/cswteams/ms3/rest/HolidayRestEndpoint.java
Correzzione dell'URL di connessione dal EndPoint dei giorni di vacanza, l'url inserito "https://date.nager.at/api/v3/PublicHolidays"
=> Close #255

src/main/java/org/cswteams/ms3/control/preferenze/CalendarSetting.java
=> Deprecate CalendarSettings

frontend/src/components/common/CustomAppointmentComponents.js, frontend/src/views/utente/ScheduleView.js
Interfaccia relativa all'utente. ref #318
=> Implementazione dell'interfaccia di richiesta di ritiro dal turno

src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
- slash
- migliore gestione eccezioni anti-HTTP.500
- valori di ritorno REST endpoint
=> Issue #318: backend, minor fixes and improvements

src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java, src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java, src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
ref. #318 
- storico richieste (task B6)
- +REST endpoint `leggiRichiesteRimozioneDaTurnoPerUtente`
- caricamento allegati (task B7)
- +REST endpoint `caricaAllegato`
- aggiornati _DAO_, _DTO_, _controller_, interfaccia _controller_, mappatore
Resta da discutere l'implementazione della gestione lato _Pianificatore_, magari in _sprint_ successivi.
=> Issue #318 - backend, post-sprint 2

pom.xml, src/main/java/org/cswteams/ms3/config/AppConfig.java, src/main/java/org/cswteams/ms3/config/ValidatorAspectBean.java, src/main/java/org/cswteams/ms3/jpa_constraints/validant/Validant.java, src/main/java/org/cswteams/ms3/jpa_constraints/validant/ValidantAspect.java, src/main/resources/application.properties, src/test/java/org/cswteams/ms3/TestValidant.java, src/test/java/org/cswteams/ms3/ValidantTestClass.java
Se definitivo le issues saranno chiuse.
Nota : Questa commit non tocca classi legate alla schedulazione dei turni, pertanto dovrebbe essere mergeabile senza problemi
=> Risoluzione issue #333 and #298

src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
ref. #318
ripristinata gestione risoluzione richiesta
=> Issue #318: backend, functionality restore

src/main/java/org/cswteams/ms3/control/assegnazioneTurni/ControllerAssegnazioniTurni.java, src/main/java/org/cswteams/ms3/control/assegnazioneTurni/IControllerAssegnazioneTurni.java, src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java, src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java, src/main/java/org/cswteams/ms3/entity/AssegnazioneTurno.java, src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java, src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
=> Issue #318, backend, task B8

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/API/RequestTurnChange.js, frontend/src/API/RequestTurnChangeAPI.js, frontend/src/components/common/AssegnazioneTurnoModificaComponent.js, frontend/src/data/sidebar-nav-items.js, frontend/src/routes.js, frontend/src/views/utente/TurnChangeView.js, src/main/java/org/cswteams/ms3/config/ApplicationStartup.java, src/main/java/org/cswteams/ms3/control/preferenze/CalendarSetting.java, src/main/java/org/cswteams/ms3/control/preferenze/CalendarSettingBuilder.java, src/main/java/org/cswteams/ms3/control/preferenze/ICalendarServiceManager.java, src/main/java/org/cswteams/ms3/control/scambioTurno/ControllerScambioTurno.java, src/main/java/org/cswteams/ms3/control/scambioTurno/IControllerScambioTurno.java, src/main/java/org/cswteams/ms3/control/scheduler/ControllerScheduler.java, src/main/java/org/cswteams/ms3/control/scheduler/IControllerScheduler.java, src/main/java/org/cswteams/ms3/dao/RequestTurnChangeDao.java, src/main/java/org/cswteams/ms3/dao/UtenteDao.java, src/main/java/org/cswteams/ms3/dto/AssegnazioneTurnoDTO.java, src/main/java/org/cswteams/ms3/dto/RequestTurnChangeDto.java, src/main/java/org/cswteams/ms3/dto/ViewUserTurnRequestsDTO.java, src/main/java/org/cswteams/ms3/entity/AssegnazioneTurno.java, src/main/java/org/cswteams/ms3/entity/Request.java, src/main/java/org/cswteams/ms3/enums/RequestENUM.java, src/main/java/org/cswteams/ms3/rest/AssegnazioneTurnoRestEndpoint.java, src/test/java/org/cswteams/ms3/control/preferenze/CalendarSettingTest.java
closed #6 (Richiesta di scambio turno)
Updated #7 (Risposta richiesta di scambio)
=> Richiesta di scambio turno

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/views/configuratore/ConfigurazioneVincoli.js, frontend/src/views/configuratore/RegistraUtenteView.js, frontend/src/views/pianificatore/ScheduleGeneratorView.js, frontend/src/views/utente/CambiaPasswordView.js, frontend/src/views/utente/Preference.js, frontend/src/views/utente/ScheduleView.js, frontend/src/views/utente/SingleScheduleView.js, frontend/src/views/utente/UserProfilesView.js, src/main/java/org/cswteams/ms3/config/ApplicationStartup.java, src/main/java/org/cswteams/ms3/control/concreteShift/ConcreteShiftController.java, src/main/java/org/cswteams/ms3/control/registrazione/ControllerRegistrazione.java, src/main/java/org/cswteams/ms3/dao/ConcreteShiftDAO.java, src/main/java/org/cswteams/ms3/entity/ConcreteShift.java, src/main/java/org/cswteams/ms3/entity/Doctor.java, src/main/java/org/cswteams/ms3/entity/DoctorAssignment.java, src/main/java/org/cswteams/ms3/entity/User.java, src/main/java/org/cswteams/ms3/rest/ConcreteShiftRestEndpoint.java
=> Revert "branch sync"

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/API/ShiftChangeRequestAPI.js, frontend/src/API/UserAPI.js, frontend/src/components/common/AssegnazioneTurnoModificaComponent.js, frontend/src/components/common/CustomAppointmentComponents.js, frontend/src/views/utente/ShiftChangeView.js, src/main/java/org/cswteams/ms3/control/concreteShift/ConcreteShiftController.java, src/main/java/org/cswteams/ms3/control/scambioTurno/ControllerScambioTurno.java, src/main/java/org/cswteams/ms3/control/scambioTurno/IControllerScambioTurno.java, src/main/java/org/cswteams/ms3/dao/ConcreteShiftDAO.java, src/main/java/org/cswteams/ms3/dao/ShiftChangeRequestDAO.java, src/main/java/org/cswteams/ms3/dto/AnswerTurnChangeRequestDTO.java, src/main/java/org/cswteams/ms3/dto/concreteshift/GetAllConcreteShiftDTO.java, src/main/java/org/cswteams/ms3/entity/DoctorAssignment.java, src/main/java/org/cswteams/ms3/rest/ConcreteShiftRestEndpoint.java, src/main/java/org/cswteams/ms3/rest/ShiftChangeRequestRestEndpoint.java
fix non documentati nel frontend
notati problemi nella gestione dei task su DoctorAssignment
=> storia #7 completata

src/main/java/org/cswteams/ms3/config/ApplicationStartup.java
changed hardcoded days for scheduling to current day and current day + one week
=> fix to make the system run

frontend/src/API/ServizioAPI.js, frontend/src/components/common/BottomViewCreaServizio.js, src/main/java/org/cswteams/ms3/control/medicalService/IMedicalServiceController.java, src/main/java/org/cswteams/ms3/control/medicalService/MedicalServiceController.java, src/main/java/org/cswteams/ms3/control/task/ITaskController.java, src/main/java/org/cswteams/ms3/control/task/TaskController.java, src/main/java/org/cswteams/ms3/dto/medicalservice/MedicalServiceCreationDTO.java, src/main/java/org/cswteams/ms3/dto/medicalservice/MedicalServiceDTO.java, src/main/java/org/cswteams/ms3/rest/MedicalServicesRestEndpoint.java
ref. #74 - tutto funzionante, a meno di ulteriori variazioni minime
=> Issue #74, first raw solution

frontend/src/API/HolidaysAPI.js, frontend/src/data/sidebar-nav-items.js, frontend/src/routes.js, frontend/src/views/configuratore/InserisciFestivita.js, src/main/java/org/cswteams/ms3/control/preferenze/HolidayController.java, src/main/java/org/cswteams/ms3/control/preferenze/IHolidayController.java, src/main/java/org/cswteams/ms3/dao/RecurrentHolidayDAO.java, src/main/java/org/cswteams/ms3/dto/holidays/CustomHolidayDTOIn.java, src/main/java/org/cswteams/ms3/entity/RecurrentHoliday.java, src/main/java/org/cswteams/ms3/rest/HolidayRestEndpoint.java, src/main/java/org/cswteams/ms3/utils/day_and_month/DayAndMonth.java, src/main/java/org/cswteams/ms3/utils/day_and_month/DayAndMonthValidator.java, src/main/java/org/cswteams/ms3/utils/day_and_month/DaysAndMonths.java, src/main/java/org/cswteams/ms3/utils/start_end_day_month/StartEndDayMonth.java, src/main/java/org/cswteams/ms3/utils/start_end_day_month/StartEndMonthValidator.java
This pull request addresses issue #73, allowing insertion of manually defined events. These events are also visible from the main calendar
=> Issue 73 : manual event insertion

frontend/src/API/ServizioAPI.js, frontend/src/components/common/BottomViewCreaServizio.js, frontend/src/components/common/BottomViewModificaServizio.js, frontend/src/components/common/DialogEliminaServizio.js, frontend/src/entity/MedicalService.js, frontend/src/entity/Task.js, frontend/src/views/configuratore/MedicalServicesView.js, src/main/java/org/cswteams/ms3/control/medicalService/IMedicalServiceController.java, src/main/java/org/cswteams/ms3/control/medicalService/MedicalServiceController.java, src/main/java/org/cswteams/ms3/dao/MedicalServiceDAO.java, src/main/java/org/cswteams/ms3/dao/TaskDAO.java, src/main/java/org/cswteams/ms3/dto/medicalservice/MedicalServiceDTO.java, src/main/java/org/cswteams/ms3/dto/medicalservice/MedicalServiceWithTaskAssignmentsDTO.java, src/main/java/org/cswteams/ms3/dto/medicalservice/TaskWithAssignmentDTO.java, src/main/java/org/cswteams/ms3/entity/DoctorAssignment.java, src/main/java/org/cswteams/ms3/entity/MedicalService.java, src/main/java/org/cswteams/ms3/rest/MedicalServicesRestEndpoint.java
=> Close #413

frontend/src/components/common/PreferencesDatePick.js
Adapted checkboxes displaying in preferences view. #409
=> Issue #409 resolution

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/API/DoctorAPI.js, frontend/src/components/common/AssegnazioneTurnoModificaComponent.js, frontend/src/entity/Doctor.js, src/main/java/org/cswteams/ms3/config/ApplicationStartup.java, src/main/java/org/cswteams/ms3/control/doctor/DoctorController.java, src/main/java/org/cswteams/ms3/control/doctor/IDoctorController.java, src/main/java/org/cswteams/ms3/control/scambioTurno/ControllerScambioTurno.java, src/main/java/org/cswteams/ms3/control/scambioTurno/IControllerScambioTurno.java, src/main/java/org/cswteams/ms3/dao/ConcreteShiftDAO.java, src/main/java/org/cswteams/ms3/dao/DoctorDAO.java, src/main/java/org/cswteams/ms3/dto/concreteshift/GetAvailableUsersForReplacementDTO.java, src/main/java/org/cswteams/ms3/rest/ConcreteShiftRestEndpoint.java, src/main/java/org/cswteams/ms3/rest/DoctorRestEndpoint.java
The checks are only present on the shift structure, but not on the contraints.
=> Resolved issues #389 and (partially) #42

src/main/java/org/cswteams/ms3/dao/NotificationDAO.java
nella mia ultima pull request non avevo incluso un file
=> NotificationDAO

src/main/java/org/cswteams/ms3/control/scambioTurno/ControllerScambioTurno.java, src/main/java/org/cswteams/ms3/control/scambioTurno/IControllerScambioTurno.java, src/main/java/org/cswteams/ms3/dao/DoctorHolidaysDAO.java, src/main/java/org/cswteams/ms3/dao/DoctorUffaPriorityDAO.java, src/main/java/org/cswteams/ms3/rest/ConcreteShiftRestEndpoint.java
Now all constraints are checked
=> Resolved issue #42

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/entity/Doctor.js, src/main/java/org/cswteams/ms3/control/scambioTurno/ControllerScambioTurno.java, src/main/java/org/cswteams/ms3/dao/DoctorUffaPriorityDAO.java, src/main/java/org/cswteams/ms3/rest/ConcreteShiftRestEndpoint.java
Si è cercato di mettere una correzzione alla causa della scomparsa dei dottori per un determianato scambio turno ma bisogna rivedere meglio
=> Correzione problema di scambio turno

frontend/src/API/HolidaysAPI.js, frontend/src/components/common/FestivitaInseriteList.js, frontend/src/components/common/InserisciFestivitaForm.js, frontend/src/data/sidebar-nav-items.js, frontend/src/routes.js, frontend/src/views/configuratore/InserisciFestivita.js, src/main/java/org/cswteams/ms3/control/preferenze/HolidayController.java, src/main/java/org/cswteams/ms3/control/preferenze/IHolidayController.java, src/main/java/org/cswteams/ms3/dao/HolidayDAO.java, src/main/java/org/cswteams/ms3/dto/holidays/CustomHolidayIdDTO.java, src/main/java/org/cswteams/ms3/dto/holidays/CustomHolidaysDTOOut.java, src/main/java/org/cswteams/ms3/dto/holidays/NormalCustomHolidayDTOOut.java, src/main/java/org/cswteams/ms3/dto/holidays/RecurrentHolidayDTOOut.java, src/main/java/org/cswteams/ms3/entity/Holiday.java, src/main/java/org/cswteams/ms3/entity/QuantityShiftSeniority.java, src/main/java/org/cswteams/ms3/entity/RecurrentHoliday.java, src/main/java/org/cswteams/ms3/entity/scocciature/ScocciaturaVacanza.java, src/main/java/org/cswteams/ms3/rest/HolidayRestEndpoint.java
This pull request should close #73
=> Issue 73 read delete

analyzer/measurerAndAnalyzer.py, analyzer/startAnalyser.sh, frontend/src/API/AssegnazioneTurnoAPI.js, src/main/java/org/cswteams/ms3/control/vincoli/ConstraintController.java, src/main/java/org/cswteams/ms3/dao/ConfigVincoloMaxPeriodoConsecutivoDAO.java, src/main/java/org/cswteams/ms3/rest/ScheduleRestEndpoint.java
nel refactor di ConfigVincoloMaxPeriodoConsecutivo si era cambiato il nome di una variabile da italiano a inglese ma la query effettuata  tramite nome interfaccia di ConfigVincoloMaxPeriodoConsecutivoDAO.java era rimasta in italiano e per tanto non avviava l'applicazione poiche non poteva creare la query
=>  inserimento analizzatore e correzione di un bug

analyzer/measurerAndAnalyzer.py, src/main/java/org/cswteams/ms3/control/scheduler/ISchedulerController2.java, src/main/java/org/cswteams/ms3/control/scheduler/SchedulerControllerUffaPoints.java, src/main/java/org/cswteams/ms3/rest/ScheduleRestEndpoint.java
=> inserimento di una nuova interfacccia per il vecchio scheduler

src/main/java/org/cswteams/ms3/control/scheduler/ScheduleBuilderUffaPoints.java, src/main/java/org/cswteams/ms3/control/scocciatura/ControllerScocciaturaUffaPoints.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintHoliday.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintMaxOrePeriodo.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintMaxPeriodoConsecutivo.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintNumeroDiRuoloTurno.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintTurniContigui.java, src/main/java/org/cswteams/ms3/entity/constraint/ConstraintUbiquita.java, src/main/java/org/cswteams/ms3/entity/constraint/ContextConstraint.java, src/main/java/org/cswteams/ms3/entity/constraint/ContextConstraintPriority.java, src/main/java/org/cswteams/ms3/entity/constraint/ContextConstraintUffaPoints.java, src/main/java/org/cswteams/ms3/entity/scheduling/algo/DoctorScheduleState.java, src/main/java/org/cswteams/ms3/entity/scheduling/algo/DoctorUffaPriority.java, src/main/java/org/cswteams/ms3/entity/scheduling/algo/DoctorXY.java, src/main/java/org/cswteams/ms3/entity/scheduling/factory/SchedulerControllerFactory.java, src/main/java/org/cswteams/ms3/rest/ScheduleRestEndpoint.java
=> Issue469: uniforming DoctorSS/DoctorUP under DoctorXY, for constraints compatibility

src/main/java/org/cswteams/ms3/entity/constraint/ContextConstraint.java
=> Issue469: both algos work now

frontend/src/components/common/BottomViewAggiungiSchedulazione.js, frontend/src/style/LoadingOverlay.css
Implemented loading screen on schedule generation
=> Resolved issue #488

frontend/src/views/utente/ScheduleView.js
La funzionalità per il filtro ora funziona.
Update #496
=> Reintrodotta funzionalità di filtro

frontend/src/views/pianificatore/ScheduleGeneratorView.js, frontend/src/views/utente/ShiftChangeView.js, frontend/src/views/utente/SingleUserProfileView.js
=> Rimossa timezone esplicita in favore di quella implicita del browser

analyzer/HypothesisTest.py, analyzer/Plotter.py
Introduzione del q2-test per verificare che la distribuizione sia uniforme
=> introduzione del Q2-test 

frontend/src/API/UploadFilesAPI.js, frontend/src/components/common/BottomViewAssegnazioneTurno.js, src/main/java/org/cswteams/ms3/control/scheduler/SchedulerController.java, src/main/java/org/cswteams/ms3/utils/start_end_day_month/StartEndMonthValidator.java
Solved #537 and other minor bugs
=> Issue 537 and more

frontend/src/API/AssegnazioneTurnoAPI.js, frontend/src/components/common/CustomAppointmentComponents.js, frontend/src/locales/en.json, frontend/src/locales/it.json, src/main/java/org/cswteams/ms3/control/concreteShift/ConcreteShiftController.java
=> Fix "Ambulatorio in Cardiologia" dummy

src/test/java/org/cswteams/ms3/control/scheduler/constraint_tests/ControllerSchedulerTest.java
Made the resulting Schedule in ControllerSchedulerTest an attributen order to make it accessible to extenders of ControllerSchedulerExtraTest
=> Edits to ControllerSchedulerTest
